[package]
name = "placeit-assistant"
version = "0.1.0"
edition = "2021"
license = "MIT"


[dependencies]
term_cursor = "0.2.1"
term_size = "0.3.2"
kusprint = "1.0.3"
itertools = "0.12.1"
regex = "1.10.4"
ron = "0.8.1"
